# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Kamran\Documents\GitHub\linksaver\src\addClass.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1113, 820)
        Dialog.setStyleSheet("background-color: rgb(68, 68, 68);\n"
"font-size: 14pt;")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(460, 40, 211, 91))
        self.label.setMouseTracking(False)
        self.label.setStyleSheet("color: rgb(253, 253, 255);\n"
"font-size:28pt;\n"
"text-align: center;")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(90, 200, 141, 41))
        self.label_2.setStyleSheet("color: rgb(255, 232, 162);\n"
"font-size: 16pt;")
        self.label_2.setObjectName("label_2")
        self.className = QtWidgets.QLineEdit(Dialog)
        self.className.setGeometry(QtCore.QRect(290, 190, 741, 71))
        self.className.setStyleSheet("color: rgb(255, 255, 255)")
        self.className.setObjectName("className")
        self.classLink = QtWidgets.QLineEdit(Dialog)
        self.classLink.setGeometry(QtCore.QRect(290, 320, 741, 71))
        self.classLink.setStyleSheet("color: rgb(255,255,255);")
        self.classLink.setObjectName("classLink")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(90, 330, 171, 41))
        self.label_3.setStyleSheet("color: rgb(255, 232, 162);\n"
"font-size: 16pt;")
        self.label_3.setObjectName("label_3")
        self.meetingLink = QtWidgets.QLineEdit(Dialog)
        self.meetingLink.setGeometry(QtCore.QRect(290, 450, 741, 71))
        self.meetingLink.setStyleSheet("color: rgb(255,255,255);")
        self.meetingLink.setObjectName("meetingLink")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(90, 460, 161, 41))
        self.label_4.setStyleSheet("color: rgb(255, 232, 162);\n"
"font-size: 16pt;")
        self.label_4.setObjectName("label_4")
        self.fourthLink = QtWidgets.QLineEdit(Dialog)
        self.fourthLink.setGeometry(QtCore.QRect(290, 580, 741, 71))
        self.fourthLink.setStyleSheet("color: rgb(255,255,255);")
        self.fourthLink.setObjectName("fourthLink")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(90, 590, 141, 41))
        self.label_5.setStyleSheet("color: rgb(255, 232, 162);\n"
"font-size: 16pt;")
        self.label_5.setObjectName("label_5")
        self.classEntered = QtWidgets.QPushButton(Dialog)
        self.classEntered.setGeometry(QtCore.QRect(0, 720, 1111, 101))
        self.classEntered.setStyleSheet("background-color: rgb(206, 197, 146)")
        self.classEntered.setObjectName("classEntered")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Add a Class"))
        self.label_2.setText(_translate("Dialog", "Class Name"))
        self.label_3.setText(_translate("Dialog", "Course Materials"))
        self.label_4.setText(_translate("Dialog", "Meeting Link"))
        self.label_5.setText(_translate("Dialog", "Other Link"))
        self.classEntered.setText(_translate("Dialog", "Enter"))
